module.exports = {
    purge: ['./pages/**/*.js*', './components/**/*.js*'],
    darkMode: false, // or 'media' or 'class'
    theme: {
        fontFamily: {
            sans: ['Manrope', 'Lato', 'sans-serif'],
        },
        colors: {
            primary: {
                dark: '#141338',
                grey: '#52516B',
                maroon: '#B31E50',
                orange: '#F9A736',
                blue: '#414483',
                pink: '#eb4e87',
                indigo: '#414483',
                saladLight: '#77ECC8',
            },
            secondary: {
                salad: '#77ECC8',
                saladLight: 'rgba(119, 236, 200, 0.1)',
                grey: '#E2E2EB',
                lightGrey: 'rgba(242,241,241, 0.55)',
                pink: '#EB4E87',
                yellow: '#F4D779',
                blue: '#58C2FF',
                cleaningGold: '#F5D156',
                upholsteryPink: '#FF6487',
            },
            surfaceGrey: '#F6FBFF',
            white: '#F6FBFF',
            whiteStandard: '#FFFFFF',
            accountBlue: '#414483',
            borderColor: '#EDEEEF',
        },
        container: {
            center: true,
        },
        extend: {
            fontSize: {
                '12px': '12px',
                '14px': '14px',
                '16px': '16px',
                '18px': '18px',
                '22px': '22px',
                '24px': '24px',
                '25px': '25px',
                '28px': '28px',
                '32px': '32px',
                '38px': '38px',
                '40px': '40px',
                '44px': '44px',
                '45px': '45px',
                '48px': '48px',
                '78px': '78px',
            },
            spacing: {
                '4px': '4px',
                '8px': '8px',
                '16px': '16px',
                '24px': '24px',
                '32px': '32px',
                '40px': '40px',
                '48px': '48px',
                '64px': '64px',
                '128px': '128px',
                '240px': '240px',
            },
            boxShadow: {
                surface1: '0px 0px 4px 2px rgba(0, 0, 0, 0.05)',
                surface2: '0px 0px 14px rgba(0, 0, 0, 0.05)',
            },
        },
    },
    variants: {
        extend: {},
    },
    plugins: [],
};
